# Generated by Django 5.0.2 on 2024-04-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id_nota', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(max_length=200)),
                ('conteudo', models.TextField(max_length=5000)),
            ],
        ),
    ]
