# Generated by Django 5.0.2 on 2024-04-23 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='conteudo',
            new_name='conteudo_db',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='titulo',
            new_name='titulo_db',
        ),
    ]
