# Generated by Django 5.0.2 on 2024-04-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_usuario', '0002_rename_conteudo_nota_conteudo_db_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='topico',
            field=models.TextField(choices=[(1, 'Outros'), (2, 'Trabalho'), (3, 'Estudos'), (4, 'Lembretes')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
