# Generated by Django 5.0.2 on 2024-02-27 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_usuario', '0002_rename_notas_nota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='conteudo_nota',
            new_name='conteudo',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='titulo_nota',
            new_name='titulo',
        ),
    ]
