# Generated by Django 5.0.2 on 2024-04-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_usuario', '0005_nota_topico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='topico',
            field=models.TextField(choices=[(1, 'Outros'), (2, 'Trabalho'), (3, 'Estudos'), (4, 'Lembretes')], default=1, max_length=1),
        ),
    ]
